// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: emoine_r/v1/general_api.proto

package emoine_rv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// default: 10
	Limit *int32 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// default: 0
	Offset *int32 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetEventsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetEventsRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type GetEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total  int32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Events []*Event `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetEventsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *Event `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *GetEventResponse) Reset() {
	*x = GetEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResponse) ProtoMessage() {}

func (x *GetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResponse.ProtoReflect.Descriptor instead.
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type GetEventCommentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
}

func (x *GetEventCommentsRequest) Reset() {
	*x = GetEventCommentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventCommentsRequest) ProtoMessage() {}

func (x *GetEventCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetEventCommentsRequest) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventCommentsRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type GetEventCommentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comments []*Comment `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
}

func (x *GetEventCommentsResponse) Reset() {
	*x = GetEventCommentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventCommentsResponse) ProtoMessage() {}

func (x *GetEventCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventCommentsResponse.ProtoReflect.Descriptor instead.
func (*GetEventCommentsResponse) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetEventCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type GetEventReactionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
}

func (x *GetEventReactionsRequest) Reset() {
	*x = GetEventReactionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventReactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventReactionsRequest) ProtoMessage() {}

func (x *GetEventReactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventReactionsRequest.ProtoReflect.Descriptor instead.
func (*GetEventReactionsRequest) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetEventReactionsRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type GetEventReactionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// reactions are sorted by created_at asc (oldest first)
	Reactions []*Reaction `protobuf:"bytes,1,rep,name=reactions,proto3" json:"reactions,omitempty"`
}

func (x *GetEventReactionsResponse) Reset() {
	*x = GetEventReactionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventReactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventReactionsResponse) ProtoMessage() {}

func (x *GetEventReactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventReactionsResponse.ProtoReflect.Descriptor instead.
func (*GetEventReactionsResponse) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetEventReactionsResponse) GetReactions() []*Reaction {
	if x != nil {
		return x.Reactions
	}
	return nil
}

type ConnectToEventStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
}

func (x *ConnectToEventStreamRequest) Reset() {
	*x = ConnectToEventStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectToEventStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectToEventStreamRequest) ProtoMessage() {}

func (x *ConnectToEventStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectToEventStreamRequest.ProtoReflect.Descriptor instead.
func (*ConnectToEventStreamRequest) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectToEventStreamRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type ConnectToEventStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to StreamEvent:
	//
	//	*ConnectToEventStreamResponse_Event
	//	*ConnectToEventStreamResponse_Comment
	//	*ConnectToEventStreamResponse_Reaction
	StreamEvent isConnectToEventStreamResponse_StreamEvent `protobuf_oneof:"stream_event"`
}

func (x *ConnectToEventStreamResponse) Reset() {
	*x = ConnectToEventStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectToEventStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectToEventStreamResponse) ProtoMessage() {}

func (x *ConnectToEventStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectToEventStreamResponse.ProtoReflect.Descriptor instead.
func (*ConnectToEventStreamResponse) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{9}
}

func (m *ConnectToEventStreamResponse) GetStreamEvent() isConnectToEventStreamResponse_StreamEvent {
	if m != nil {
		return m.StreamEvent
	}
	return nil
}

func (x *ConnectToEventStreamResponse) GetEvent() *Event {
	if x, ok := x.GetStreamEvent().(*ConnectToEventStreamResponse_Event); ok {
		return x.Event
	}
	return nil
}

func (x *ConnectToEventStreamResponse) GetComment() *Comment {
	if x, ok := x.GetStreamEvent().(*ConnectToEventStreamResponse_Comment); ok {
		return x.Comment
	}
	return nil
}

func (x *ConnectToEventStreamResponse) GetReaction() *Reaction {
	if x, ok := x.GetStreamEvent().(*ConnectToEventStreamResponse_Reaction); ok {
		return x.Reaction
	}
	return nil
}

type isConnectToEventStreamResponse_StreamEvent interface {
	isConnectToEventStreamResponse_StreamEvent()
}

type ConnectToEventStreamResponse_Event struct {
	Event *Event `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type ConnectToEventStreamResponse_Comment struct {
	Comment *Comment `protobuf:"bytes,2,opt,name=comment,proto3,oneof"`
}

type ConnectToEventStreamResponse_Reaction struct {
	Reaction *Reaction `protobuf:"bytes,3,opt,name=reaction,proto3,oneof"`
}

func (*ConnectToEventStreamResponse_Event) isConnectToEventStreamResponse_StreamEvent() {}

func (*ConnectToEventStreamResponse_Comment) isConnectToEventStreamResponse_StreamEvent() {}

func (*ConnectToEventStreamResponse_Reaction) isConnectToEventStreamResponse_StreamEvent() {}

type SendCommentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId     string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Text        string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	IsAnonymous bool   `protobuf:"varint,3,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"`
	Color       string `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *SendCommentRequest) Reset() {
	*x = SendCommentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommentRequest) ProtoMessage() {}

func (x *SendCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommentRequest.ProtoReflect.Descriptor instead.
func (*SendCommentRequest) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{10}
}

func (x *SendCommentRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SendCommentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendCommentRequest) GetIsAnonymous() bool {
	if x != nil {
		return x.IsAnonymous
	}
	return false
}

func (x *SendCommentRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type SendCommentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comment *Comment `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *SendCommentResponse) Reset() {
	*x = SendCommentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommentResponse) ProtoMessage() {}

func (x *SendCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommentResponse.ProtoReflect.Descriptor instead.
func (*SendCommentResponse) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{11}
}

func (x *SendCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type SendReactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	StampId string `protobuf:"bytes,2,opt,name=stamp_id,json=stampId,proto3" json:"stamp_id,omitempty"`
}

func (x *SendReactionRequest) Reset() {
	*x = SendReactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReactionRequest) ProtoMessage() {}

func (x *SendReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReactionRequest.ProtoReflect.Descriptor instead.
func (*SendReactionRequest) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{12}
}

func (x *SendReactionRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SendReactionRequest) GetStampId() string {
	if x != nil {
		return x.StampId
	}
	return ""
}

type SendReactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reaction *Reaction `protobuf:"bytes,1,opt,name=reaction,proto3" json:"reaction,omitempty"`
}

func (x *SendReactionResponse) Reset() {
	*x = SendReactionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendReactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReactionResponse) ProtoMessage() {}

func (x *SendReactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReactionResponse.ProtoReflect.Descriptor instead.
func (*SendReactionResponse) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{13}
}

func (x *SendReactionResponse) GetReaction() *Reaction {
	if x != nil {
		return x.Reaction
	}
	return nil
}

var File_emoine_r_v1_general_api_proto protoreflect.FileDescriptor

var file_emoine_r_v1_general_api_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x18, 0x65, 0x6d,
	0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x88,
	0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x09, 0x0a, 0x07,
	0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x55, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x12, 0x2a, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x21,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x3c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22,
	0x34, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x30, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x22, 0x35, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x50, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x6d, 0x6f,
	0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x09, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x38, 0x0a, 0x1b,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0xc1, 0x01, 0x0a, 0x1c, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x54, 0x6f, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65,
	0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00,
	0x52, 0x08, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0e, 0x0a, 0x0c, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x7c, 0x0a, 0x12, 0x53, 0x65,
	0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x41, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x45, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2e, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x4b, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x14,
	0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x72,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x83, 0x05, 0x0a, 0x11, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x6c, 0x41, 0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1d, 0x2e, 0x65, 0x6d, 0x6f,
	0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x65, 0x6d, 0x6f, 0x69,
	0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x5f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x24, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x65,
	0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x25, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e,
	0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x26, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6d, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x54, 0x6f, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12,
	0x28, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x65, 0x6d, 0x6f, 0x69,
	0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54,
	0x6f, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x50, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64,
	0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e,
	0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x65, 0x6d, 0x6f,
	0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0xac, 0x01,
	0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76,
	0x31, 0x42, 0x0f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x41, 0x70, 0x69, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x74, 0x72, 0x61, 0x50, 0x74, 0x69, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x45, 0x6d, 0x6f, 0x69,
	0x6e, 0x65, 0x5f, 0x52, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x67, 0x65, 0x6e, 0x2f, 0x65,
	0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x65, 0x6d, 0x6f, 0x69, 0x6e,
	0x65, 0x5f, 0x72, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x45, 0x58, 0x58, 0xaa, 0x02, 0x0a, 0x45, 0x6d,
	0x6f, 0x69, 0x6e, 0x65, 0x52, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0a, 0x45, 0x6d, 0x6f, 0x69, 0x6e,
	0x65, 0x52, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x16, 0x45, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x52, 0x5c,
	0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x0b, 0x45, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x52, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_emoine_r_v1_general_api_proto_rawDescOnce sync.Once
	file_emoine_r_v1_general_api_proto_rawDescData = file_emoine_r_v1_general_api_proto_rawDesc
)

func file_emoine_r_v1_general_api_proto_rawDescGZIP() []byte {
	file_emoine_r_v1_general_api_proto_rawDescOnce.Do(func() {
		file_emoine_r_v1_general_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_emoine_r_v1_general_api_proto_rawDescData)
	})
	return file_emoine_r_v1_general_api_proto_rawDescData
}

var file_emoine_r_v1_general_api_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_emoine_r_v1_general_api_proto_goTypes = []interface{}{
	(*GetEventsRequest)(nil),             // 0: emoine_r.v1.GetEventsRequest
	(*GetEventsResponse)(nil),            // 1: emoine_r.v1.GetEventsResponse
	(*GetEventRequest)(nil),              // 2: emoine_r.v1.GetEventRequest
	(*GetEventResponse)(nil),             // 3: emoine_r.v1.GetEventResponse
	(*GetEventCommentsRequest)(nil),      // 4: emoine_r.v1.GetEventCommentsRequest
	(*GetEventCommentsResponse)(nil),     // 5: emoine_r.v1.GetEventCommentsResponse
	(*GetEventReactionsRequest)(nil),     // 6: emoine_r.v1.GetEventReactionsRequest
	(*GetEventReactionsResponse)(nil),    // 7: emoine_r.v1.GetEventReactionsResponse
	(*ConnectToEventStreamRequest)(nil),  // 8: emoine_r.v1.ConnectToEventStreamRequest
	(*ConnectToEventStreamResponse)(nil), // 9: emoine_r.v1.ConnectToEventStreamResponse
	(*SendCommentRequest)(nil),           // 10: emoine_r.v1.SendCommentRequest
	(*SendCommentResponse)(nil),          // 11: emoine_r.v1.SendCommentResponse
	(*SendReactionRequest)(nil),          // 12: emoine_r.v1.SendReactionRequest
	(*SendReactionResponse)(nil),         // 13: emoine_r.v1.SendReactionResponse
	(*Event)(nil),                        // 14: emoine_r.v1.Event
	(*Comment)(nil),                      // 15: emoine_r.v1.Comment
	(*Reaction)(nil),                     // 16: emoine_r.v1.Reaction
}
var file_emoine_r_v1_general_api_proto_depIdxs = []int32{
	14, // 0: emoine_r.v1.GetEventsResponse.events:type_name -> emoine_r.v1.Event
	14, // 1: emoine_r.v1.GetEventResponse.event:type_name -> emoine_r.v1.Event
	15, // 2: emoine_r.v1.GetEventCommentsResponse.comments:type_name -> emoine_r.v1.Comment
	16, // 3: emoine_r.v1.GetEventReactionsResponse.reactions:type_name -> emoine_r.v1.Reaction
	14, // 4: emoine_r.v1.ConnectToEventStreamResponse.event:type_name -> emoine_r.v1.Event
	15, // 5: emoine_r.v1.ConnectToEventStreamResponse.comment:type_name -> emoine_r.v1.Comment
	16, // 6: emoine_r.v1.ConnectToEventStreamResponse.reaction:type_name -> emoine_r.v1.Reaction
	15, // 7: emoine_r.v1.SendCommentResponse.comment:type_name -> emoine_r.v1.Comment
	16, // 8: emoine_r.v1.SendReactionResponse.reaction:type_name -> emoine_r.v1.Reaction
	0,  // 9: emoine_r.v1.GeneralAPIService.GetEvents:input_type -> emoine_r.v1.GetEventsRequest
	2,  // 10: emoine_r.v1.GeneralAPIService.GetEvent:input_type -> emoine_r.v1.GetEventRequest
	4,  // 11: emoine_r.v1.GeneralAPIService.GetEventComments:input_type -> emoine_r.v1.GetEventCommentsRequest
	6,  // 12: emoine_r.v1.GeneralAPIService.GetEventReactions:input_type -> emoine_r.v1.GetEventReactionsRequest
	8,  // 13: emoine_r.v1.GeneralAPIService.ConnectToEventStream:input_type -> emoine_r.v1.ConnectToEventStreamRequest
	10, // 14: emoine_r.v1.GeneralAPIService.SendComment:input_type -> emoine_r.v1.SendCommentRequest
	12, // 15: emoine_r.v1.GeneralAPIService.SendReaction:input_type -> emoine_r.v1.SendReactionRequest
	1,  // 16: emoine_r.v1.GeneralAPIService.GetEvents:output_type -> emoine_r.v1.GetEventsResponse
	3,  // 17: emoine_r.v1.GeneralAPIService.GetEvent:output_type -> emoine_r.v1.GetEventResponse
	5,  // 18: emoine_r.v1.GeneralAPIService.GetEventComments:output_type -> emoine_r.v1.GetEventCommentsResponse
	7,  // 19: emoine_r.v1.GeneralAPIService.GetEventReactions:output_type -> emoine_r.v1.GetEventReactionsResponse
	9,  // 20: emoine_r.v1.GeneralAPIService.ConnectToEventStream:output_type -> emoine_r.v1.ConnectToEventStreamResponse
	11, // 21: emoine_r.v1.GeneralAPIService.SendComment:output_type -> emoine_r.v1.SendCommentResponse
	13, // 22: emoine_r.v1.GeneralAPIService.SendReaction:output_type -> emoine_r.v1.SendReactionResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_emoine_r_v1_general_api_proto_init() }
func file_emoine_r_v1_general_api_proto_init() {
	if File_emoine_r_v1_general_api_proto != nil {
		return
	}
	file_emoine_r_v1_schema_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_emoine_r_v1_general_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventCommentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventCommentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventReactionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventReactionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectToEventStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectToEventStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCommentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCommentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendReactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendReactionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_emoine_r_v1_general_api_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_emoine_r_v1_general_api_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*ConnectToEventStreamResponse_Event)(nil),
		(*ConnectToEventStreamResponse_Comment)(nil),
		(*ConnectToEventStreamResponse_Reaction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_emoine_r_v1_general_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emoine_r_v1_general_api_proto_goTypes,
		DependencyIndexes: file_emoine_r_v1_general_api_proto_depIdxs,
		MessageInfos:      file_emoine_r_v1_general_api_proto_msgTypes,
	}.Build()
	File_emoine_r_v1_general_api_proto = out.File
	file_emoine_r_v1_general_api_proto_rawDesc = nil
	file_emoine_r_v1_general_api_proto_goTypes = nil
	file_emoine_r_v1_general_api_proto_depIdxs = nil
}
