// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package schema

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Comment defines model for Comment.
type Comment struct {
	Color       string    `json:"color"`
	CreatedAt   time.Time `json:"created_at"`
	Id          CommentId `json:"id"`
	IsAnonymous bool      `json:"is_anonymous"`
	MeetingId   MeetingId `json:"meeting_id"`
	Text        string    `json:"text"`
	UserId      string    `json:"user_id"`
}

// CommentId defines model for CommentId.
type CommentId = openapi_types.UUID

// CreateMeetingRequest defines model for CreateMeetingRequest.
type CreateMeetingRequest struct {
	Description string `json:"description"`
	VideoId     string `json:"video_id"`
}

// CreateToken defines model for CreateToken.
type CreateToken struct {
	Description string    `json:"description"`
	ExpireAt    time.Time `json:"expire_at"`
	MeetingId   MeetingId `json:"meeting_id"`
	UserId      string    `json:"user_id"`
}

// Meeting defines model for Meeting.
type Meeting struct {
	Description string    `json:"description"`
	EndedAt     time.Time `json:"ended_at"`
	Id          MeetingId `json:"id"`
	StartedAt   time.Time `json:"started_at"`
	Thumbnail   string    `json:"thumbnail"`
	Title       string    `json:"title"`
	VideoId     string    `json:"video_id"`
}

// MeetingId defines model for MeetingId.
type MeetingId = openapi_types.UUID

// MeetingsWithTotal defines model for MeetingsWithTotal.
type MeetingsWithTotal struct {
	Meetings []Meeting `json:"meetings"`
	Total    int       `json:"total"`
}

// Reaction defines model for Reaction.
type Reaction struct {
	CreatedAt time.Time  `json:"created_at"`
	Id        ReactionId `json:"id"`
	MeetingId MeetingId  `json:"meeting_id"`
	StampId   string     `json:"stamp_id"`
	UserId    string     `json:"user_id"`
}

// ReactionId defines model for ReactionId.
type ReactionId = openapi_types.UUID

// Token defines model for Token.
type Token struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatorId   string    `json:"creator_id"`
	Description string    `json:"description"`
	ExpireAt    time.Time `json:"expire_at"`
	MeetingId   MeetingId `json:"meeting_id"`
	Token       string    `json:"token"`
	UserId      string    `json:"user_id"`
}

// Tokens defines model for Tokens.
type Tokens struct {
	Meeting Meeting `json:"meeting"`
	Token   Token   `json:"token"`
}

// LimitInQuery defines model for limitInQuery.
type LimitInQuery = int

// MeetingIdInPath defines model for meetingIdInPath.
type MeetingIdInPath = MeetingId

// OffsetInQuery defines model for offsetInQuery.
type OffsetInQuery = int

// SessionsInCookie defines model for sessionsInCookie.
type SessionsInCookie = string

// TokenInPath defines model for tokenInPath.
type TokenInPath = string

// GetAllMeetingsParams defines parameters for GetAllMeetings.
type GetAllMeetingsParams struct {
	// Limit 取得する件数
	Limit *LimitInQuery `form:"limit,omitempty" query:"limit" json:"limit,omitempty"`

	// Offset 取得を開始する件数（0-index）
	Offset *OffsetInQuery `form:"offset,omitempty" query:"offset" json:"offset,omitempty"`
}

// CallbackParams defines parameters for Callback.
type CallbackParams struct {
	// Code OAuth2.0のcode
	Code     string            `form:"code" json:"code"`
	Sessions *SessionsInCookie `form:"sessions,omitempty" json:"sessions,omitempty"`
}

// CreateMeetingJSONRequestBody defines body for CreateMeeting for application/json ContentType.
type CreateMeetingJSONRequestBody = CreateMeetingRequest

// UpdateMeetingJSONRequestBody defines body for UpdateMeeting for application/json ContentType.
type UpdateMeetingJSONRequestBody = CreateMeetingRequest

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody = CreateToken

// PatchTokenJSONRequestBody defines body for PatchToken for application/json ContentType.
type PatchTokenJSONRequestBody = Token
