// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: emoine_r/v1/general_api.proto

package emoine_rv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMeetingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetMeetingsRequest) Reset() {
	*x = GetMeetingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMeetingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingsRequest) ProtoMessage() {}

func (x *GetMeetingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingsRequest.ProtoReflect.Descriptor instead.
func (*GetMeetingsRequest) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetMeetingsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMeetingsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetMeetingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total    int64      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Meetings []*Meeting `protobuf:"bytes,2,rep,name=meetings,proto3" json:"meetings,omitempty"`
}

func (x *GetMeetingsResponse) Reset() {
	*x = GetMeetingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMeetingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingsResponse) ProtoMessage() {}

func (x *GetMeetingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingsResponse.ProtoReflect.Descriptor instead.
func (*GetMeetingsResponse) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetMeetingsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetMeetingsResponse) GetMeetings() []*Meeting {
	if x != nil {
		return x.Meetings
	}
	return nil
}

type GetMeetingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMeetingRequest) Reset() {
	*x = GetMeetingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingRequest) ProtoMessage() {}

func (x *GetMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingRequest.ProtoReflect.Descriptor instead.
func (*GetMeetingRequest) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetMeetingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMeetingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meeting *Meeting `protobuf:"bytes,1,opt,name=meeting,proto3" json:"meeting,omitempty"`
}

func (x *GetMeetingResponse) Reset() {
	*x = GetMeetingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMeetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingResponse) ProtoMessage() {}

func (x *GetMeetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingResponse.ProtoReflect.Descriptor instead.
func (*GetMeetingResponse) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetMeetingResponse) GetMeeting() *Meeting {
	if x != nil {
		return x.Meeting
	}
	return nil
}

type GetMeetingCommentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeetingId string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
}

func (x *GetMeetingCommentsRequest) Reset() {
	*x = GetMeetingCommentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMeetingCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingCommentsRequest) ProtoMessage() {}

func (x *GetMeetingCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetMeetingCommentsRequest) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetMeetingCommentsRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

type GetMeetingCommentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comments []*Comment `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
}

func (x *GetMeetingCommentsResponse) Reset() {
	*x = GetMeetingCommentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMeetingCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingCommentsResponse) ProtoMessage() {}

func (x *GetMeetingCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingCommentsResponse.ProtoReflect.Descriptor instead.
func (*GetMeetingCommentsResponse) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetMeetingCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type GetMeetingReactionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeetingId string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
}

func (x *GetMeetingReactionsRequest) Reset() {
	*x = GetMeetingReactionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMeetingReactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingReactionsRequest) ProtoMessage() {}

func (x *GetMeetingReactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingReactionsRequest.ProtoReflect.Descriptor instead.
func (*GetMeetingReactionsRequest) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetMeetingReactionsRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

type GetMeetingReactionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reactions []*Reaction `protobuf:"bytes,1,rep,name=reactions,proto3" json:"reactions,omitempty"`
}

func (x *GetMeetingReactionsResponse) Reset() {
	*x = GetMeetingReactionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMeetingReactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingReactionsResponse) ProtoMessage() {}

func (x *GetMeetingReactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingReactionsResponse.ProtoReflect.Descriptor instead.
func (*GetMeetingReactionsResponse) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetMeetingReactionsResponse) GetReactions() []*Reaction {
	if x != nil {
		return x.Reactions
	}
	return nil
}

type ConnectToMeetingStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeetingId string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
}

func (x *ConnectToMeetingStreamRequest) Reset() {
	*x = ConnectToMeetingStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectToMeetingStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectToMeetingStreamRequest) ProtoMessage() {}

func (x *ConnectToMeetingStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectToMeetingStreamRequest.ProtoReflect.Descriptor instead.
func (*ConnectToMeetingStreamRequest) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectToMeetingStreamRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

type ConnectToMeetingStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*ConnectToMeetingStreamResponse_Meeting
	//	*ConnectToMeetingStreamResponse_Comment
	//	*ConnectToMeetingStreamResponse_Reaction
	Event isConnectToMeetingStreamResponse_Event `protobuf_oneof:"event"`
}

func (x *ConnectToMeetingStreamResponse) Reset() {
	*x = ConnectToMeetingStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectToMeetingStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectToMeetingStreamResponse) ProtoMessage() {}

func (x *ConnectToMeetingStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectToMeetingStreamResponse.ProtoReflect.Descriptor instead.
func (*ConnectToMeetingStreamResponse) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{9}
}

func (m *ConnectToMeetingStreamResponse) GetEvent() isConnectToMeetingStreamResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *ConnectToMeetingStreamResponse) GetMeeting() *Meeting {
	if x, ok := x.GetEvent().(*ConnectToMeetingStreamResponse_Meeting); ok {
		return x.Meeting
	}
	return nil
}

func (x *ConnectToMeetingStreamResponse) GetComment() *Comment {
	if x, ok := x.GetEvent().(*ConnectToMeetingStreamResponse_Comment); ok {
		return x.Comment
	}
	return nil
}

func (x *ConnectToMeetingStreamResponse) GetReaction() *Reaction {
	if x, ok := x.GetEvent().(*ConnectToMeetingStreamResponse_Reaction); ok {
		return x.Reaction
	}
	return nil
}

type isConnectToMeetingStreamResponse_Event interface {
	isConnectToMeetingStreamResponse_Event()
}

type ConnectToMeetingStreamResponse_Meeting struct {
	Meeting *Meeting `protobuf:"bytes,1,opt,name=meeting,proto3,oneof"`
}

type ConnectToMeetingStreamResponse_Comment struct {
	Comment *Comment `protobuf:"bytes,2,opt,name=comment,proto3,oneof"`
}

type ConnectToMeetingStreamResponse_Reaction struct {
	Reaction *Reaction `protobuf:"bytes,3,opt,name=reaction,proto3,oneof"`
}

func (*ConnectToMeetingStreamResponse_Meeting) isConnectToMeetingStreamResponse_Event() {}

func (*ConnectToMeetingStreamResponse_Comment) isConnectToMeetingStreamResponse_Event() {}

func (*ConnectToMeetingStreamResponse_Reaction) isConnectToMeetingStreamResponse_Event() {}

type SendCommentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeetingId   string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	Text        string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	IsAnonymous bool   `protobuf:"varint,3,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"`
	Color       string `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *SendCommentRequest) Reset() {
	*x = SendCommentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommentRequest) ProtoMessage() {}

func (x *SendCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommentRequest.ProtoReflect.Descriptor instead.
func (*SendCommentRequest) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{10}
}

func (x *SendCommentRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *SendCommentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendCommentRequest) GetIsAnonymous() bool {
	if x != nil {
		return x.IsAnonymous
	}
	return false
}

func (x *SendCommentRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type SendCommentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comment *Comment `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *SendCommentResponse) Reset() {
	*x = SendCommentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommentResponse) ProtoMessage() {}

func (x *SendCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommentResponse.ProtoReflect.Descriptor instead.
func (*SendCommentResponse) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{11}
}

func (x *SendCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type SendReactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeetingId string `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	StampId   string `protobuf:"bytes,2,opt,name=stamp_id,json=stampId,proto3" json:"stamp_id,omitempty"`
}

func (x *SendReactionRequest) Reset() {
	*x = SendReactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendReactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReactionRequest) ProtoMessage() {}

func (x *SendReactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReactionRequest.ProtoReflect.Descriptor instead.
func (*SendReactionRequest) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{12}
}

func (x *SendReactionRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *SendReactionRequest) GetStampId() string {
	if x != nil {
		return x.StampId
	}
	return ""
}

type SendReactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reaction *Reaction `protobuf:"bytes,1,opt,name=reaction,proto3" json:"reaction,omitempty"`
}

func (x *SendReactionResponse) Reset() {
	*x = SendReactionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emoine_r_v1_general_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendReactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReactionResponse) ProtoMessage() {}

func (x *SendReactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emoine_r_v1_general_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReactionResponse.ProtoReflect.Descriptor instead.
func (*SendReactionResponse) Descriptor() ([]byte, []int) {
	return file_emoine_r_v1_general_api_proto_rawDescGZIP(), []int{13}
}

func (x *SendReactionResponse) GetReaction() *Reaction {
	if x != nil {
		return x.Reaction
	}
	return nil
}

var File_emoine_r_v1_general_api_proto protoreflect.FileDescriptor

var file_emoine_r_v1_general_api_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x18, 0x65, 0x6d,
	0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x65,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x5d, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x30, 0x0a, 0x08, 0x6d, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x65, 0x6d, 0x6f, 0x69,
	0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52,
	0x08, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x44,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x6d, 0x65, 0x65,
	0x74, 0x69, 0x6e, 0x67, 0x22, 0x3a, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64,
	0x22, 0x4e, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30,
	0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0x3b, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x52, 0x0a,
	0x1b, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x09,
	0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x3e, 0x0a, 0x1d, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x4d, 0x65,
	0x65, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49,
	0x64, 0x22, 0xc2, 0x01, 0x0a, 0x1e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x4d,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x07, 0x6d,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x30, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65,
	0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x6d, 0x6f,
	0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x07, 0x0a,
	0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x80, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x41, 0x6e, 0x6f, 0x6e, 0x79, 0x6d,
	0x6f, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x45, 0x0a, 0x13, 0x53, 0x65, 0x6e,
	0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2e, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x22, 0x4f, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x65,
	0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x49,
	0x64, 0x22, 0x49, 0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x72, 0x65, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x6d,
	0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x08, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xa1, 0x05, 0x0a,
	0x11, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x41, 0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x50, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x12, 0x1f, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x12, 0x1e, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e,
	0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x26, 0x2e, 0x65, 0x6d, 0x6f, 0x69,
	0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x27, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x27, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x65, 0x6d, 0x6f,
	0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x65, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x73, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54,
	0x6f, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x2a,
	0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x65, 0x6d, 0x6f,
	0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x54, 0x6f, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x50, 0x0a, 0x0b, 0x53, 0x65, 0x6e,
	0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e,
	0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x65, 0x6d, 0x6f, 0x69,
	0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0c, 0x53,
	0x65, 0x6e, 0x64, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x2e, 0x65, 0x6d,
	0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0xad, 0x01, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f,
	0x72, 0x2e, 0x76, 0x31, 0x42, 0x0f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x41, 0x70, 0x69,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x72, 0x61, 0x50, 0x74, 0x69, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x45,
	0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x52, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x62, 0x75, 0x66, 0x67,
	0x65, 0x6e, 0x2f, 0x65, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x65,
	0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x45, 0x58, 0x58, 0xaa,
	0x02, 0x0a, 0x45, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x52, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0a, 0x45,
	0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x52, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x16, 0x45, 0x6d, 0x6f, 0x69,
	0x6e, 0x65, 0x52, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x0b, 0x45, 0x6d, 0x6f, 0x69, 0x6e, 0x65, 0x52, 0x3a, 0x3a, 0x56, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_emoine_r_v1_general_api_proto_rawDescOnce sync.Once
	file_emoine_r_v1_general_api_proto_rawDescData = file_emoine_r_v1_general_api_proto_rawDesc
)

func file_emoine_r_v1_general_api_proto_rawDescGZIP() []byte {
	file_emoine_r_v1_general_api_proto_rawDescOnce.Do(func() {
		file_emoine_r_v1_general_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_emoine_r_v1_general_api_proto_rawDescData)
	})
	return file_emoine_r_v1_general_api_proto_rawDescData
}

var file_emoine_r_v1_general_api_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_emoine_r_v1_general_api_proto_goTypes = []interface{}{
	(*GetMeetingsRequest)(nil),             // 0: emoine_r.v1.GetMeetingsRequest
	(*GetMeetingsResponse)(nil),            // 1: emoine_r.v1.GetMeetingsResponse
	(*GetMeetingRequest)(nil),              // 2: emoine_r.v1.GetMeetingRequest
	(*GetMeetingResponse)(nil),             // 3: emoine_r.v1.GetMeetingResponse
	(*GetMeetingCommentsRequest)(nil),      // 4: emoine_r.v1.GetMeetingCommentsRequest
	(*GetMeetingCommentsResponse)(nil),     // 5: emoine_r.v1.GetMeetingCommentsResponse
	(*GetMeetingReactionsRequest)(nil),     // 6: emoine_r.v1.GetMeetingReactionsRequest
	(*GetMeetingReactionsResponse)(nil),    // 7: emoine_r.v1.GetMeetingReactionsResponse
	(*ConnectToMeetingStreamRequest)(nil),  // 8: emoine_r.v1.ConnectToMeetingStreamRequest
	(*ConnectToMeetingStreamResponse)(nil), // 9: emoine_r.v1.ConnectToMeetingStreamResponse
	(*SendCommentRequest)(nil),             // 10: emoine_r.v1.SendCommentRequest
	(*SendCommentResponse)(nil),            // 11: emoine_r.v1.SendCommentResponse
	(*SendReactionRequest)(nil),            // 12: emoine_r.v1.SendReactionRequest
	(*SendReactionResponse)(nil),           // 13: emoine_r.v1.SendReactionResponse
	(*Meeting)(nil),                        // 14: emoine_r.v1.Meeting
	(*Comment)(nil),                        // 15: emoine_r.v1.Comment
	(*Reaction)(nil),                       // 16: emoine_r.v1.Reaction
}
var file_emoine_r_v1_general_api_proto_depIdxs = []int32{
	14, // 0: emoine_r.v1.GetMeetingsResponse.meetings:type_name -> emoine_r.v1.Meeting
	14, // 1: emoine_r.v1.GetMeetingResponse.meeting:type_name -> emoine_r.v1.Meeting
	15, // 2: emoine_r.v1.GetMeetingCommentsResponse.comments:type_name -> emoine_r.v1.Comment
	16, // 3: emoine_r.v1.GetMeetingReactionsResponse.reactions:type_name -> emoine_r.v1.Reaction
	14, // 4: emoine_r.v1.ConnectToMeetingStreamResponse.meeting:type_name -> emoine_r.v1.Meeting
	15, // 5: emoine_r.v1.ConnectToMeetingStreamResponse.comment:type_name -> emoine_r.v1.Comment
	16, // 6: emoine_r.v1.ConnectToMeetingStreamResponse.reaction:type_name -> emoine_r.v1.Reaction
	15, // 7: emoine_r.v1.SendCommentResponse.comment:type_name -> emoine_r.v1.Comment
	16, // 8: emoine_r.v1.SendReactionResponse.reaction:type_name -> emoine_r.v1.Reaction
	0,  // 9: emoine_r.v1.GeneralAPIService.GetMeetings:input_type -> emoine_r.v1.GetMeetingsRequest
	2,  // 10: emoine_r.v1.GeneralAPIService.GetMeeting:input_type -> emoine_r.v1.GetMeetingRequest
	4,  // 11: emoine_r.v1.GeneralAPIService.GetMeetingComments:input_type -> emoine_r.v1.GetMeetingCommentsRequest
	6,  // 12: emoine_r.v1.GeneralAPIService.GetMeetingReactions:input_type -> emoine_r.v1.GetMeetingReactionsRequest
	8,  // 13: emoine_r.v1.GeneralAPIService.ConnectToMeetingStream:input_type -> emoine_r.v1.ConnectToMeetingStreamRequest
	10, // 14: emoine_r.v1.GeneralAPIService.SendComment:input_type -> emoine_r.v1.SendCommentRequest
	12, // 15: emoine_r.v1.GeneralAPIService.SendReaction:input_type -> emoine_r.v1.SendReactionRequest
	1,  // 16: emoine_r.v1.GeneralAPIService.GetMeetings:output_type -> emoine_r.v1.GetMeetingsResponse
	3,  // 17: emoine_r.v1.GeneralAPIService.GetMeeting:output_type -> emoine_r.v1.GetMeetingResponse
	5,  // 18: emoine_r.v1.GeneralAPIService.GetMeetingComments:output_type -> emoine_r.v1.GetMeetingCommentsResponse
	7,  // 19: emoine_r.v1.GeneralAPIService.GetMeetingReactions:output_type -> emoine_r.v1.GetMeetingReactionsResponse
	9,  // 20: emoine_r.v1.GeneralAPIService.ConnectToMeetingStream:output_type -> emoine_r.v1.ConnectToMeetingStreamResponse
	11, // 21: emoine_r.v1.GeneralAPIService.SendComment:output_type -> emoine_r.v1.SendCommentResponse
	13, // 22: emoine_r.v1.GeneralAPIService.SendReaction:output_type -> emoine_r.v1.SendReactionResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_emoine_r_v1_general_api_proto_init() }
func file_emoine_r_v1_general_api_proto_init() {
	if File_emoine_r_v1_general_api_proto != nil {
		return
	}
	file_emoine_r_v1_schema_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_emoine_r_v1_general_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMeetingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMeetingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMeetingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMeetingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMeetingCommentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMeetingCommentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMeetingReactionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMeetingReactionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectToMeetingStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectToMeetingStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCommentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCommentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendReactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emoine_r_v1_general_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendReactionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_emoine_r_v1_general_api_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*ConnectToMeetingStreamResponse_Meeting)(nil),
		(*ConnectToMeetingStreamResponse_Comment)(nil),
		(*ConnectToMeetingStreamResponse_Reaction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_emoine_r_v1_general_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emoine_r_v1_general_api_proto_goTypes,
		DependencyIndexes: file_emoine_r_v1_general_api_proto_depIdxs,
		MessageInfos:      file_emoine_r_v1_general_api_proto_msgTypes,
	}.Build()
	File_emoine_r_v1_general_api_proto = out.File
	file_emoine_r_v1_general_api_proto_rawDesc = nil
	file_emoine_r_v1_general_api_proto_goTypes = nil
	file_emoine_r_v1_general_api_proto_depIdxs = nil
}
